### ISSUE TITLE
您好，这些用于评估的生成视频可以公开一下吗

### ISSUE THREAD

**Issue by LongMa-2025** [llyx97/FETV#1]

**Comment by llyx97** [comment]
当然，您可以从这些link中下载[cogvideo_outputs](https://drive.google.com/file/d/1ZQ3O0qjb1QS7jFy3JxD_NlU6BSnvTmzA/view?usp=sharing), [text2video-zero_outputs](https://drive.google.com/file/d/1PtDtglbYcwe4vr1GAEV7fICnomTo62D2/view?usp=drive_link), [modelscope-t2v_outputs](https://drive.google.com/file/d/12LeifL95GlkcDPlspoBkUiHg4RD--IlR/view?usp=drive_link), [zeroscope_outputs](https://drive.google.com/file/d/1YjOjpS2IJg26pez7LF0kQHKZZEK3fbGR/view?usp=drive_link)

**Comment by LongMa-2025** [comment]
非常感谢，你们的工作给了我很大启发，期待你们的evaluaton代码。
