### ISSUE TITLE
Prompt的分类与选择

### ISSUE THREAD

**Issue by xiefan233** [llyx97/FETV#2]
您好，我对您工作中的Prompt的分类与选择比较感兴趣。
首先，WordNet Synsets是如何使用的呢，我有点不太明白。例如，'animal.n.01'，里面包含['animal', 'animate_being', 'beast', 'brute', 'creature', 'fauna']，之后对于一个Prompt，我们是遍历Prompt中每一个单词，看是否有和这个列表中相匹配的吗？
其次，我发现每个属性下的words都比较少，真的能够有效的分类吗？例如color属性下Key Phrases/Words，只有'white'。

**Comment by llyx97** [comment]
感谢您对我们工作的关注。
关于WordNet Synsets的使用，您的理解大致是正确的，不过我们不止会匹配'animal.n.01'的lemmas。具体而言，我们会遍历prompt中的单词，只要有一个单词的synset的hypernym_paths中包含'animal.n.01'，那么这个prompt就会被归类为Animals。
关于每个属性下Key Phrases/Words较少，这是因为WordNet Synset已经可以匹配到大部分的情况。

**Comment by xiefan233** [comment]
> 感谢您对我们工作的关注。 关于WordNet Synsets的使用，您的理解大致是正确的，不过我们不止会匹配'animal.n.01'的lemmas。具体而言，我们会遍历prompt中的单词，只要有一个单词的synset的hypernym_paths中包含'animal.n.01'，那么这个prompt就会被归类为Animals。 关于每个属性下Key Phrases/Words较少，这是因为WordNet Synset已经可以匹配到大部分的情况。

感谢回答！还有一个问题是Camera View中的WordNet Synsets为什么没有像其他一样的词性后缀？
![image](https://github.com/llyx97/FETV/assets/44406605/0afc796d-069b-4224-be63-12b7e39e6edc)

**Comment by llyx97** [comment]
这个Table有些地方确实写错了，感谢您指出这个问题！我们之后会修正的

**Comment by LongMa-2025** [comment]
这部分代码可以公开一下吗 @llyx97
