### ISSUE TITLE
Which UMT models used in UMTScore?

### ISSUE THREAD

**Issue by KaiyueSun98** [llyx97/FETV#4]
Hi, thanks for your great work, I would like to confirm which UMT model (finetuned stage) you used to calculate the UMTScore? Video-text retrieval or VQA ![1](https://github.com/llyx97/FETV/assets/94892075/8c7290f7-13c7-4bb5-abb3-bc982c7469c6)
![2](https://github.com/llyx97/FETV/assets/94892075/5b095a31-9485-4ebc-9b02-d8ab4d0418c6)

**Comment by llyx97** [comment]
Thanks for your attention to our work!
We adopt the version fine-tuned on video-text retrieval.

**Comment by KaiyueSun98** [comment]
> Thanks for your attention to our work! We adopt the version fine-tuned on video-text retrieval.

Many thanks!
